# Generated by Django 2.1.7 on 2019-02-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
