# Generated by Django 2.1.7 on 2019-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190217_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
